# Generated by Django 4.1.5 on 2023-02-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('NUR', 'NUR'), ('LKG', 'LKG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('nationalitly', models.CharField(choices=[('india', 'india'), ('other', 'other')], max_length=100)),
                ('state', models.CharField(choices=[('bihar', 'bihar'), ('other', 'other')], max_length=100)),
                ('city', models.CharField(choices=[('purnia', 'purnia'), ('other', 'other')], max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=30)),
                ('pin', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='media')),
                ('className', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.classes')),
            ],
        ),
    ]
