# Generated by Django 4.1.5 on 2023-02-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
