# Generated by Django 4.1.5 on 2023-02-13 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='className',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.classes'),
        ),
    ]
