# Generated by Django 4.1.5 on 2023-02-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, help_text='use MM/DD/YYY', null=True),
        ),
    ]
